[profile.mainnet] 
# RISC Zero Verifier contract deployed on mainnet (see https://dev.risczero.com/api/blockchain-integration/contracts/verifier#deployed-verifiers)
chainId = 1
riscZeroVerifierAddress = "0x8EaB2D97Dfce405A1692a21b3ff3A172d593D319"
genesisBlockTimestamp = 1606824000

[profile.sepolia]
# RISC Zero Verifier contract deployed on sepolia (see https://dev.risczero.com/api/blockchain-integration/contracts/verifier#deployed-verifiers)
chainId = 11155111
riscZeroVerifierAddress = "0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187"
genesisBlockTimestamp = 1655733600

# You can add additional profiles here
[profile.anvil]
# anvil, deploy a new set of risczero verifier contracts each time
riscZeroVerifierAddress = "0x0000000000000000000000000000000000000000"
chainId = 31337
genesisBlockTimestamp = 0
