[package]
name = "tracing-risc0"
version.workspace = true
edition.workspace = true

[dependencies]
risc0-zkvm = { workspace = true, default-features = false, features = ['std'] }
tracing-subscriber = { version = "0.3.19" }
tracing = "0.1.41"
