[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
test = "test"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.5/src/",
    "openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "risc0/=dependencies/risc0-2.0.0/contracts/src/",
]

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.1.0"
risc0 = { version = "2.0.0", git = "https://github.com/risc0/risc0-ethereum.git", tag = "v2.0.0" }

[soldeer]
remappings_generate = true
remappings_version = false
remappings_location = "config"
