[package]
name = "beacon-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ssz_rs = { workspace = true }
ethereum-consensus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
